info:
  component: DiscoveryService

server:
  port: 8761
  
spring:
  application:
    name: eureka-discovery-service
 
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost